sonar.projectKey=wke0715_eip
sonar.organization=wke0715

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/.next/**,**/e2e/**,**/__tests__/**
sonar.typescript.tsconfigPath=tsconfig.json
